# Generated by Django 2.2.6 on 2019-10-28 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code',
            field=models.CharField(default=123, max_length=40, verbose_name='Pin Code'),
            preserve_default=False,
        ),
    ]
