# Generated by Django 2.2.6 on 2019-10-29 04:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='kid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('gender', models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=2, verbose_name='Genero')),
                ('username', models.SlugField(max_length=40)),
                ('name', models.CharField(max_length=500, verbose_name='Kid Name')),
                ('birthdate', models.DateField(verbose_name='Birthdate')),
                ('premature_date', models.DateField(blank=True, null=True, verbose_name='Premature date estimated')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Niño',
                'verbose_name_plural': 'Niños',
            },
        ),
    ]
