# Generated by Django 2.2.6 on 2019-11-08 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('gender', models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=2, verbose_name='Genero')),
                ('username', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=500, verbose_name='Kid Name')),
                ('birthdate', models.DateField(verbose_name='Birthdate')),
                ('premature_date', models.DateField(blank=True, null=True, verbose_name='Premature date estimated')),
            ],
            options={
                'verbose_name': 'Niño',
                'verbose_name_plural': 'Niños',
            },
        ),
        migrations.CreateModel(
            name='KidHeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('height', models.CharField(max_length=10, verbose_name='Height')),
                ('age_height', models.CharField(max_length=10, verbose_name='Age height')),
                ('percentile', models.CharField(max_length=10, verbose_name='Percentile')),
                ('date_height', models.DateField(verbose_name='Date Heigth')),
                ('kid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='families.Kid')),
            ],
            options={
                'verbose_name': 'Altura Niño',
                'verbose_name_plural': 'Alturas de los Niño',
            },
        ),
    ]
