# Generated by Django 2.2.6 on 2019-11-10 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0002_kid_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='OmsMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=2, verbose_name='Gender')),
                ('age', models.FloatField(verbose_name='Age kid')),
                ('l_size', models.FloatField(default=1, verbose_name='L data')),
                ('m_size', models.FloatField(verbose_name='M data')),
                ('s_size', models.FloatField(verbose_name='S data')),
            ],
            options={
                'verbose_name': 'OMS measurement',
                'verbose_name_plural': 'OMS measurements',
            },
        ),
        migrations.CreateModel(
            name='SAPMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=2, verbose_name='Gender')),
                ('age', models.FloatField(verbose_name='Age kid')),
                ('median', models.FloatField(verbose_name='Median')),
                ('standard_desviation', models.FloatField(verbose_name='Standar desviation')),
            ],
            options={
                'verbose_name': 'SAP measurement',
                'verbose_name_plural': 'SAP measurements',
            },
        ),
        migrations.AlterField(
            model_name='kid',
            name='gender',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=2, verbose_name='Gender'),
        ),
    ]
