# Generated by Django 2.2.6 on 2019-11-02 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0003_kidheight'),
    ]

    operations = [
        migrations.AddField(
            model_name='kidheight',
            name='age_height',
            field=models.CharField(default='', max_length=10, verbose_name='Age height'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kidheight',
            name='percentile',
            field=models.CharField(default='', max_length=10, verbose_name='Percentile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kidheight',
            name='kid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='families.Kid'),
        ),
    ]
