# Generated by Django 2.2.6 on 2019-11-02 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0004_auto_20191102_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kidheight',
            name='height',
            field=models.CharField(max_length=10, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='kidheight',
            name='kid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='families.Kid'),
        ),
    ]
