# Generated by Django 2.2.6 on 2019-11-11 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0004_auto_20191111_0210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kidheight',
            options={'verbose_name': 'Altura Niño', 'verbose_name_plural': 'Alturas de los Niños'},
        ),
        migrations.AlterField(
            model_name='kidheight',
            name='age_height',
            field=models.CharField(help_text='Age in months at measurement moment.', max_length=10, verbose_name='Age height'),
        ),
    ]
