# Generated by Django 2.2.6 on 2019-11-14 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0005_auto_20191111_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='kid',
            name='is_premature',
            field=models.BooleanField(default=False, verbose_name='Is premature'),
        ),
    ]
