# Generated by Django 2.2.6 on 2019-11-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0006_kid_is_premature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kid',
            name='premature_date',
        ),
        migrations.AddField(
            model_name='kid',
            name='premature_weaks',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Premature weaks'),
        ),
    ]
