# Generated by Django 2.2.6 on 2019-11-20 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0007_auto_20191120_0636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kid',
            old_name='premature_weaks',
            new_name='premature_weeks',
        ),
    ]
